package com.osa.loan.calc;

import com.osa.loan.calc.model.*;
import com.osa.loan.calc.service.*;

dialect  "java"

global Double totalPayments;
global Utils utils;

rule "1: Opłaty za mieszkanie."
    when
        $person :Person()
        $bills : MonthlyBills(estate > 0) from $person.bills
    then
        totalPayments += $bills.getEstate();
end

rule "2: Koszty utrzymania."
    when
        $person :Person()
        $bills : MonthlyBills(living > 0) from $person.bills
    then
        totalPayments += $bills.getLiving();
end

rule "3: Składki ubezpieczeniowe."
    when
        $person :Person()
        $bills : MonthlyBills(insurance > 0) from $person.bills
    then
        totalPayments += $bills.getInsurance();
end

rule "4: Inne kredyty."
    when
        $person :Person()
        $bills : MonthlyBills(otherLoans > 0) from $person.bills
    then
        totalPayments += $bills.getOtherLoans();
end

rule "5: Pozostałe koszta."
    when
        $person :Person()
        $bills : MonthlyBills(others > 0) from $person.bills
    then
        totalPayments += $bills.getOthers();
end

rule "6: Klient pracujący"
    when
        $person : Person(monthlySalary > 0)
        $results : Results()
    then
        modify($results){ setUnemployed(false) };
end

rule "7: Klient bezrobotny"
    when
        $person : Person(monthlySalary == 0)
        $results : Results()
    then
        modify($results){ setUnemployed(true) };
end

rule "8: Małżonka pracująca"
    when
        $person : Person(married == true, partnerMonthlySalary > 0)
        $results : Results()
    then
        modify($results){ setPartnerUnemployed(false) };
end

rule "9: Małżonka bezrobotna"
    when
        $person : Person(married == true, partnerMonthlySalary == 0)
        $results : Results()
    then
        modify($results){ setPartnerUnemployed(true) };
end

rule "10: Klient nie wypłacalny"
    when
        $person : Person(monthlySalary < totalPayments)
        $results : Results()
    then
        modify($results){ setAbleToPayBills(false) };
end

rule "11: Klient wypłacalny"
    when
        $person : Person(monthlySalary >= totalPayments)
        $results : Results()
    then
        modify($results){ setAbleToPayBills(true) };
end

rule "12: Klient z małżonkiem nie wypłacalni"
    when
        $person : Person(monthlySalary + partnerMonthlySalary < totalPayments)
        $results : Results()
    then
        modify($results){ setAbleToPayBills(false) };
end

rule "13: Klient z małżonkiem wypłacalni"
    when
        $person : Person(monthlySalary + partnerMonthlySalary >= totalPayments)
        $results : Results()
    then
        modify($results){ setAbleToPayBills(true) };
end

rule "14: Klient nie jest w stanie sam opłacać rat"
    when
        $person : Person(monthlySalary < (totalPayments + loan.monthlyLoanInstallment))
        $loan : Loan(monthlyLoanInstallment > 0) from $person.loan
        $results : Results()
    then
        modify($results){ setAbleToPayInstallments(false) };
end

rule "15: Klient jest w stanie sam opłacać rat"
    when
        $person : Person(monthlySalary >= (totalPayments + loan.monthlyLoanInstallment))
        $loan : Loan(monthlyLoanInstallment > 0) from $person.loan
        $results : Results()
    then
        modify($results){ setAbleToPayInstallments(false) };
end

rule "16: Klient z małżonkiem nie jest w stanie opłacać rat"
    when
        $person : Person(married == true, monthlySalary + partnerMonthlySalary < (totalPayments + loan.monthlyLoanInstallment))
        $loan : Loan(monthlyLoanInstallment > 0) from $person.loan
        $results : Results()
    then
        modify($results){ setAbleToPayInstallmentsWithPartner(false) };
end

rule "17: Klient z małżonkiem jest w stanie opłacać rat"
    when
        $person : Person(married == true, monthlySalary + partnerMonthlySalary >= (totalPayments + loan.monthlyLoanInstallment))
        $loan : Loan(monthlyLoanInstallment > 0) from $person.loan
        $results : Results()
    then
        modify($results){ setAbleToPayInstallmentsWithPartner(false) };
end