package com.osa.loan.calc;
import com.osa.loan.calc.model.*;
import java.util.*;
import java.time.*;
import org.slf4j.Logger;

dialect  "java"

global Logger log;
global Verdict verdict;

rule "34: Klient nie wystarczająco stary"
    no-loop true
    when
        $results : Results(oldEnough == false)
    then
        verdict.addCritical();
        log.debug("rule 34");
end

rule "35: Klient zbyt stary"
    no-loop true
    when
        $person : Person(married == false)
        $results : Results(tooOld == true)
    then
        verdict.addCritical();
        log.debug("rule 35");
end

rule "36: Klient i małżonka zbyt starzy"
    no-loop true
    when
        $person : Person(married == true, children == 0)
        $results : Results(tooOld == true, partnerTooOld == true)
    then
        verdict.addCritical();
        log.debug("rule 36");
end

rule "37: Klient bez dochodów"
    no-loop true
    when
        $person : Person(married == false)
        $results: Results(unemployed == true)
    then
        verdict.addCritical();
        log.debug("rule 37");
end

rule "38: Klient bez dochodów"
    no-loop true
    when
        $person : Person(married == true)
        $results: Results(unemployed == true, partnerUnemployed == true)
    then
        verdict.addCritical();
        log.debug("rule 38");
end

rule "39: Nie starcza na rachunki"
    no-loop true
    when
        $person : Person(married == false)
        $results: Results(ableToPayBills == false)
    then
        verdict.addCritical();
        log.debug("rule 39");
end

rule "40: Nie starcza na rachunki"
    no-loop true
    when
        $person : Person(married == true)
        $results: Results(ableToPayBills == false, ableToPayBillsWithPartner == false)
    then
        verdict.addCritical();
        log.debug("rule 40");
end

rule "41: Nie starcza na raty"
    no-loop true
    when
        $person : Person(married == false)
        $results: Results(ableToPayBills == true, ableToPayInstallments == false)
    then
        verdict.addCritical();
        log.debug("rule 41");
end

rule "42: Nie starcza na raty"
    no-loop true
    when
        $person : Person(married == true)
        $results: Results(ableToPayBillsWithPartner == true, ableToPayInstallments == false, ableToPayInstallmentsWithPartner == false)
    then
        verdict.addCritical();
        log.debug("rule 42");
end

rule "43: Bez małżonka nie da rady"
    no-loop true
    when
        $person : Person(married == true)
        $results : Results(ableToPayBills == false, ableToPayBillsWithPartner == true)
    then
        verdict.addWarning()
            .addWarning();
        log.debug("rule 43");
end

rule "44: Bez małżonka nie da rady"
    no-loop true
    when
        $person : Person(married == true)
        $results : Results(ableToPayBills == true, ableToPayInstallments == false, ableToPayInstallmentsWithPartner == true)
    then
        verdict.addWarning();
        log.debug("rule 44");
end

rule "45: Może sam płacić rachunki"
    no-loop true
    when
        $results : Results(ableToPayBills == true)
    then
        verdict.addPositive();
        log.debug("rule 45");
end

rule "46: Może sam płacić raty"
    no-loop true
    when
        $results : Results(ableToPayInstallments == true)
    then
        verdict.addPositive()
            .addPositive();
        log.debug("rule 46");
end

rule "47: Spłaci całość"
    no-loop true
    when
        $results : Results(willClientLiveLongEnough == true)
    then
        verdict.addPositive()
            .addPositive();
        log.debug("rule 47");
end

rule "48: Spłaci całość z małżonkiem"
    no-loop true
    when
        $results : Results(willClientLiveLongEnough == false, willClientsPartnerLiveLongEnough == true)
    then
        verdict.addPositive()
            .addWarning();
        log.debug("rule 48");
end

rule "49: Dzieci mogą spłacić resztę"
    no-loop true
    when
        $results : Results(willClientLiveLongEnough == false, childCanCarryOnAfterClient == true)
    then
        verdict.addPositive()
            .addWarning()
            .addWarning();
        log.debug("rule 49");
end

rule "50: Dzieci mogą spłacić resztę"
    no-loop true
    when
        $results : Results(!willClientLiveLongEnough && !willClientsPartnerLiveLongEnough && (childCanCarryOnAfterClient || childCanCarryOnAfterPartner))
    then
        verdict.addPositive()
            .addWarning()
            .addWarning()
            .addWarning();
        log.debug("rule 50");
end

rule "50: Nie można spłacić do końca"
    no-loop true
    when
        $results : Results(willClientLiveLongEnough == false,
                           willClientsPartnerLiveLongEnough == false,
                           childCanCarryOnAfterClient == false,
                           childCanCarryOnAfterPartner == false)
    then
        verdict.addCritical();
        log.debug("rule 51");
end