package com.osa.loan.calc;
import com.osa.loan.calc.model.*;
import java.util.*;
import java.time.*;
import org.slf4j.Logger;

dialect  "java"

global Logger log;
global Verdict verdict;

rule "34: Klient nie wystarczająco stary"
no-loop true
salience 50
    when
        $results : Results(oldEnough == false)
    then
        verdict.addCritical();
end

rule "35: Klient zbyt stary"
no-loop true
salience 50
    when
        $person : Person(married == false)
        $results : Results(tooOld == true)
    then
        verdict.addCritical();
end

rule "36: Klient i małżonka zbyt starzy"
no-loop true
salience 49
    when
        $person : Person(married == true, children == 0)
        $results : Results(tooOld == true, partnerTooOld == true)
    then
        verdict.addCritical();
end

rule "37: Klient bez dochodów"
no-loop true
salience 49
    when
        $person : Person(married == false)
        $results: Results(unemployed == true)
    then
        verdict.addCritical();
end

rule "38: Klient z małżonką bez dochodów"
no-loop true
salience 49
    when
        $person : Person(married == true)
        $results: Results(unemployed == true, partnerUnemployed == true)
    then
        verdict.addCritical();
end

rule "39: Nie starcza na rachunki"
no-loop true
salience 48
    when
        $person : Person(married == false)
        $results: Results(ableToPayBills == false)
    then
        verdict.addCritical();
end

rule "40: Nie starcza na rachunki z małżonką"
no-loop true
salience 48
    when
        $person : Person(married == true)
        $results: Results(ableToPayBills == false, ableToPayBillsWithPartner == false)
    then
        verdict.addCritical();
end

rule "41: Nie starcza na raty"
no-loop true
salience 47
    when
        $person : Person(married == false)
        $results: Results(ableToPayBills == true, ableToPayInstallments == false)
    then
        verdict.addCritical();
end

rule "42: Nie starcza na raty z małżonką"
no-loop true
salience 47
    when
        $person : Person(married == true)
        $results: Results(ableToPayBillsWithPartner == true, ableToPayInstallments == false, ableToPayInstallmentsWithPartner == false)
    then
        verdict.addCritical();
end

rule "43: Bez małżonka nie da rady"
no-loop true
salience 40
    when
        $person : Person(married == true)
        $results : Results(ableToPayBills == false, ableToPayBillsWithPartner == true)
    then
        verdict.addWarning()
            .addWarning();
end

rule "44: Bez małżonka nie da rady"
no-loop true
salience 39
    when
        $person : Person(married == true)
        $results : Results(ableToPayBills == true, ableToPayInstallments == false, ableToPayInstallmentsWithPartner == true)
    then
        verdict.addWarning();
end

rule "45: Może sam płacić rachunki"
no-loop true
salience 38
    when
        $results : Results(ableToPayBills == true)
    then
        verdict.addPositive();
end

rule "46: Może sam płacić raty"
no-loop true
salience 37
    when
        $results : Results(ableToPayInstallments == true)
    then
        verdict.addPositive()
            .addPositive();
end

rule "47: Spłaci całość"
no-loop true
salience 36
    when
        $results : Results(willClientLiveLongEnough == true)
    then
        verdict.addPositive()
            .addPositive();
end

rule "48: Spłaci całość z małżonkiem"
no-loop true
salience 35
    when
        $results : Results(willClientLiveLongEnough == false, willClientsPartnerLiveLongEnough == true)
    then
        verdict.addPositive()
            .addWarning();
end

rule "49: Dzieci mogą spłacić resztę"
no-loop true
salience 34
    when
        $results : Results(willClientLiveLongEnough == false, childCanCarryOnAfterClient == true)
    then
        verdict.addPositive()
            .addWarning()
            .addWarning();
end

rule "50: Dzieci mogą spłacić resztę"
no-loop true
salience 33
    when
        $results : Results(!willClientLiveLongEnough && !willClientsPartnerLiveLongEnough && (childCanCarryOnAfterClient || childCanCarryOnAfterPartner))
    then
        verdict.addPositive()
            .addWarning()
            .addWarning()
            .addWarning();
end

rule "51: Nie można spłacić do końca"
no-loop true
salience 33
    when
        $results : Results(willClientLiveLongEnough == false,
                           willClientsPartnerLiveLongEnough == false,
                           childCanCarryOnAfterClient == false,
                           childCanCarryOnAfterPartner == false)
    then
        verdict.addCritical();
end

rule "52: Kredyt w PLN"
no-loop true
salience 32
    when
        $person : Person()
        $loan : Loan(currency == LoanCurrency.PLN) from $person.loan
    then
        verdict.addPositive();
end

rule "53: Kredyt w obcej walucie"
no-loop true
salience 32
    when
        $person : Person()
        $loan : Loan(currency != LoanCurrency.PLN) from $person.loan
    then
        verdict.addWarning();
end